# Scaffolding generated by Casein v5.1.1.5

module Casein
  class DestinationsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Destinations'
  		@destinations = Destination.order(sort_order(:nombre)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View destination'
      @destination = Destination.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new destination'
    	@destination = Destination.new
    end

    def create
      @destination = Destination.new destination_params
    
      if @destination.save
        flash[:notice] = 'Destination created'
        redirect_to casein_destinations_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new destination'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update destination'
      
      @destination = Destination.find params[:id]
    
      if @destination.update_attributes destination_params
        flash[:notice] = 'Destination has been updated'
        redirect_to casein_destinations_path
      else
        flash.now[:warning] = 'There were problems when trying to update this destination'
        render :action => :show
      end
    end
 
    def destroy
      @destination = Destination.find params[:id]

      @destination.destroy
      flash[:notice] = 'Destination has been deleted'
      redirect_to casein_destinations_path
    end
  
    private
      
      def destination_params
        params.require(:destination).permit(:nombre, :descripcion, :link, :costo, :imagen)
      end

  end
end